config/routes.rb
Rails.application.routes.draw do

  get 'errors/not_found'

  get 'errors/unacceptable'

  get 'errors/internal_error'

  get 'errors/under_construction'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :activities
  resources :reports
  resources :relationships, only: [:create, :destroy]

  concern :permissible do
    post :public_share
    post :public_unshare
  end

  root 'static_pages#home'

  get 'static_pages/help'
  get 'static_pages/home'

  get "/404", :to => "errors#not_found"
  get "/422", :to => "errors#unacceptable"
  get "/500", :to => "errors#internal_error"
  get "/underconst", :to => "errors#under_construction"

  resources :collections do
    collection do
      get :autocomplete
      get :name_available
    end
    resources :elements
    member do
      concerns :permissible
      get :load_slideshow
    end
  end

  resources :items do
    collection do
      get :autocomplete
    end
    root to: 'items#index'
  end

  resources :posts

  get 'search/results'

  devise_for :users,
             :controllers => {
                 :registrations => 'registrations',
                 :user_profiles => 'user_profiles'
             }

  devise_scope :user do
    get :username_available, controller: "registrations"
    get :email_available, controller: "registrations"
  end

  resources :user_profiles do
    collection do
      get :autocomplete
    end
    member do
      get '/following', to: "relationships#index"
      get '/social', to: "social#index"
      get "/following_list", to: "social#following_list", as: "following_list"
    end
    resources :circles, path: "/followers"
    get "/set_users", to: "circles#set_users", as: "set_users"
  end

  concern :votable do
    member do
      put :upvote
      put :downvote
      put :unvote
    end
  end

  concern :commentable do
    resources :comments, concerns: :votable
  end

  resources :comments, concerns: :commentable, shallow: true

  resources :items, concerns: :commentable, shallow: true

  resources :collections, shallow: true do
    resources :elements, concerns: :commentable
  end

  mount Markitup::Rails::Engine, at: "markitup", as: "markitup"

end

app/models/collection.rb
class Collection < ActiveRecord::Base
  include Permissible
  include PublicActivity::Model
  
  tracked except: :destroy,owner: ->(controller, model) { controller && controller.current_user }

  belongs_to :user
  has_many :items, through: :elements
  has_many :elements, dependent: :destroy
  
  validates :user_id, presence: true
  validates :name, presence: true, :uniqueness => { scope: :user_id }, length: { maximum: 50 }
  validates :user, presence: true
  validates :description, length: { maximum: 600 }


  searchkick  autocompletable: [:name], index_name: "collections", merge_mappings: true, mappings: {
      collection: {
          properties: {
              name: {type: "string"}
          }
      }
  }

  def search_data
    {
        name: name,
        description: description,
        created: created_at,
        updated: updated_at,
        user: user_id
    }
  end

  def find_element_item_pairs
    self.elements.includes :item
  end

  def self.search_collection_auto(term, user)
    first = Collection.search(query: {prefix: {name: term}}, where: {user: user}, limit: 3).map(&:name)
    second = Collection.search(term, field: ["name"], where: {user: user}, autocompleteable: true, limit: 2, misspellings: {edit_distance: 5}).map(&:name)
    second.each { |collection| first << collection unless first.include?(collection) }
    first
  end

  def self.find_available_collections(user_id, item)
    all = Collection.where(user_id: user_id).includes(:elements).order(updated_at: :desc)
    result = []

    all.each do |collection|
      result << collection unless collection.elements.any? { |e| e.item == item }
    end
    result
  end

  def self.name_available?(name, user_id)
    !Collection.exists?(name: name, user_id: user_id)
  end

  def activity_visible_to?(user)
    self.visible_to?(user)
  end

  def cover_image
    element = self.elements.find { |e| e.get_image.present? }
    element.get_image.thumb.url unless element.nil?
  end

  def slideshow
    elements = self.elements.select { |e| e.get_image.present? }
    slideshow = elements.map { |e| e.get_image.thumb.url }
  end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  include PermissibleController

  before_action :set_collection, only: [:show, :load_slideshow]
  before_action :set_user_and_collection, only: [:edit, :update, :destroy]
  before_action :set_elements, only: [:show]
  # before_action :authenticate_user!

  helper_method :sort_param, :direction_param

  # GET /collections
  # GET /collections.json
  def index
    if params[:add_item]
      @item = Item.find(params[:add_item])
      @collections = Collection.find_available_collections(current_user.id, @item)
    elsif params[:query].present?
      @collections = Collection.search params[:query].downcase, where: {user: current_user.id}
    else
      @collections = current_user.collections
    end
  end

  def autocomplete
    render json: Collection.search_collection_auto(params[:term].downcase, current_user.id)
  end

  # GET /collections/1
  # GET /collections/1.json
  def show
    redirect_to collections_path, alert: "Requested collection not found" and return unless @collection
  end

  # GET /collections/new
  def new
    @collection = Collection.new
  end

  # GET /collections/1/edit
  def edit
  end

  # POST /collections
  # POST /collections.json
  def create
    @collection = Collection.new(collection_params)
    @collection.user_id = current_user.id

    respond_to do |format|
      if @collection.save
       if params["item_id"]
          format.html { redirect_to new_collection_element_path(@collection.id, :item_id => params["item_id"]), notice: 'Collection was successfully created.' }
          #format.json { render action: 'show', status: :created, location: new_collection_element_path(@collection.id, :item_id => params["item_id"]) }
        else
          format.html { redirect_to @collection, notice: 'Collection was successfully created.' }
          format.json { render action: 'show', status: :created, location: @collection }
        end
      else
        format.html { render action: 'new' }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collections/1
  # PATCH/PUT /collections/1.json
  def update
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to @collection, notice: 'Collection was successfully updated.' }
        format.json { render action: 'show', status: :ok, location: @collection }
      else
        format.html { render action: 'edit' }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collections/1
  # DELETE /collections/1.json
  def destroy
    @collection.elements.destroy_all
    @collection.destroy

    respond_to do |format|
      format.html { redirect_to collections_url, notice: 'Collection successfully destroyed' }
      format.json { head :no_content }
    end
  end

  def load_slideshow
    respond_to do |format|
      format.html { redirect_to @collection }
      format.js { render json: @collection.slideshow }
    end
  end

  def name_available
    valid = params[:name] == params[:current_name]
    valid ||= Collection.name_available?(params[:name], params[:user_id])
    render json: valid
  end

  private
    # Use callbacks to share common setup or constraints between actions.

  def sort_param
    Collection.column_names.include?(params[:sort]) ? params[:sort].to_sym : :name
  end

  def direction_param
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

  def set_collection
    begin
      @collection = Collection.find(params[:id])
      unless @collection.user_id == current_user.id || @collection.visible_to?(current_user)
        redirect_to(collections_path, alert: "Access forbidden")
      end
    rescue
      @collection = nil
    end
  end

  def set_user_and_collection
    begin
      @collection = Collection.find(params[:id])
      unless @collection.user_id == current_user.id
        redirect_to(collections_path, alert: "Access forbidden")
      end
    rescue
      @collection = nil
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def collection_params
    params[:collection].permit(:name, :current_name, :description, :add_item, :user_id)
  end

  def set_elements
    @elements = @collection.find_element_item_pairs unless @collection.nil?
  end

  def set_permissible
    @permissible = Collection.find(params[:id])
  end
end

app/helpers/collections_helper.rb
module CollectionsHelper

  def collection_thumb_path(collection, item)
    if item.present?
      new_collection_element_path(collection, item_id: item)
    else
      collection
    end
  end

end

app/views/collections/_collection_thumb.html.erb
<li class="collection-thumb col-xs-12 col-sm-6 col-md-3" data-action="<%= load_slideshow_collection_url collection %>" data-name="<%= collection.name %>" data-created="<%= collection.created_at.strftime("%FT%R") %>" data-updated="<%= collection.updated_at.strftime("%FT%R") %>">
  <div class="thumbnail">
    <%= link_to collection_thumb_path(collection, @item) do %>
        <div class="slideshow-wrapper">
          <div class="slideshow">
            <%= image_or_placeholder collection.cover_image %>
          </div>

          <div class="items-counter-wrapper">
            <div class="items-counter">
              <b><%= collection.elements.count %></b>
              items
            </div>
          </div>
        </div>
    <% end %>

    <div class="caption">
      <h3>
        <%= link_to collection.name, collection_thumb_path(collection, @item) %>
      </h3>
    </div>
  </div>
</li>

app/views/collections/_collectioncarousel.erb
<ul class="items_carousel main-list">
      <% @elements.each do |element| %>
          <li class="item_block item" data-name="<%= element.item.name %>" data-created="<%= element.created_at.strftime("%FT%R") %>" data-updated="<%= element.updated_at.strftime("%FT%R") %>">
            <%= link_to collection_element_path(@collection, element) do %>
                <div class="item-image">
                    <%= image_or_placeholder element.get_image.thumb.url %>
                  <div class="name-wrapper">
                    <h3 class="item-name"><%= element.item.name %></h3>
                  </div>
                </div>
                <% unless element.item_attributes.empty? %>
                    <div class="item-info attr-wrapper">
                        <ul class="attr-list">
                            <% element.item_attributes.each do |attr| %>
                                <li><% if attr.type == "state" %>
                                      <%= attr.name %> <i class="<%= attr.value ? "fa fa-plus-square-o" : "fa fa-minus-square-o" %>"></i>
                                  <% else %>
                                      <%= "#{attr.name}: #{attr.value}" %>
                                  <% end %></li>
                            <% end %>
                        </ul>
                    </div>
                <% end %>
            <% end %>
          </li>
      <% end %>
</ul>

app/views/collections/_collectiongrid.erb
<ul class="items-shelf main-list">
  <% @elements.each do |element| %>
      <li class="item-box item box-shadow" data-name="<%= element.item.name %>" data-created="<%= element.created_at.strftime("%FT%R") %>" data-updated="<%= element.updated_at.strftime("%FT%R") %>">
        <a href="<%= collection_element_path(@collection, element) %>" >
          <div class="white">
            <%= image_or_placeholder element.get_image.small_thumb.url %>
          </div>
        </a>
      </li>
  <% end %>
</ul>

app/views/collections/_collectionlist.erb
<ul class="media-list main-list" id="sortable">
  <% @elements.each do |element| %>
      <li class="media item underlined" data-name="<%= element.item.name %>" data-created="<%= element.created_at.strftime("%FT%R") %>" data-updated="<%= element.updated_at.strftime("%FT%R") %>">
        <%= link_to collection_element_path(@collection, element) do %>
          <%= image_or_placeholder element.get_image.small_thumb.url, class: "img-list media-object pull-left" %>
        <% end %>
        <%= link_to collection_element_path(@collection, element) do %>
            <div class="media-body">
              <h3>
                <%= element.item.name %>
              </h3>
              <p><%= element.description.blank? ? content_tag(:span, "No description", style: "color:grey;") : element.description %></p>
            </div>
        <% end %>
        <% unless element.item_attributes.empty? %>
            <span class="fa fa-caret-down item-details"></span>
            <div class="item-attr list-attr">
              <ul class="attr-list">
                  <% element.item_attributes.each do |attr| %>
                    <li><% if attr.type == "state" %>
                      <%= attr.name %> <i class="<%= attr.value ? "fa fa-plus-square-o" : "fa fa-minus-square-o" %>"></i>
                    <% else %>
                      <%= "#{attr.name}: #{attr.value}" %>
                    <% end %></li>
                  <% end %>
              </ul>
            </div>
        <% end %>
      </li>
  <% end %>
</ul>

app/views/collections/_collectionscounter.erb
<h3><%= pluralize(@collections.count, "result") %></h3>

app/views/collections/_collectionslist.erb
<ul class="collections-list row">
  <% collections.each do |collection| %>
    <%= render 'collections/collection_thumb', collection: collection %>
  <% end %>
</ul>

app/views/collections/_form.html.erb
<% if @collection.errors.any? %>
  <div class="row">
    <div class="bs-callout bs-callout-danger">
      <h4><%= pluralize(@collection.errors.count, "error") %> prohibited this collection from being saved:</h4>
      <ul>
        <% @collection.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

<%= form_for @collection, :html => {:id => "collection-form"} do |f| %>
    <%= hidden_field_tag "item_id", @item.id, class: "form-control free-input", placeholder: @item.id if @item %>
    <%= hidden_field_tag "user_id", current_user.id %>

    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, autofocus: true, action: name_available_collections_url, class: "form-control free-input", counter: 50 %>
    </div>

    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: "form-control free-input", counter: 600 %>
    </div>

    <div class="buttons-group">
      <ul class="horizontal">
        <li><%= f.submit nil, class: "btn btn-primary free-btn" %></li>
        <%= yield :buttons %>
      </ul>
    </div>
<% end %>

app/views/collections/edit.html.erb
<h1 class="mainpage_header">Editing collection</h1>

<% content_for :buttons do %>
    <li>
    <%= link_to [@collection], method: :delete, data: { confirm: "Are you sure you want to delete this collection?\nThis action is irreversible!" }, class: "btn btn-default" do %>
        <i class="fa fa-trash"></i>
        Delete
    <% end %>
    </li>
    <li><%= cancel_to @collection %></li>
<% end %>

<div class="col-sm-8 col-sm-offset-2 col-md-8 col-md-offset-2">
  <%= render 'form' %>
</div>

app/views/collections/index.html.erb
<h1 class="mainpage_header">
<% if @item %>
    Choose collection to add <span class="item-name"><%= @item.name %></span> <a href="<%= collections_path %>" class="fa fa-times" title="Cancel" id="cancel-addding-button"></a>
<% else %>
    Your collections
<% end %>
</h1>

<div id="collecions-search-bar">
  <div class="row underlined">
    <%= form_tag collections_path, :method => :get, :id => "collections-search" do %>
        <div class="col-md-6">
          <div class="form-group">
            <div class="input-group">
              <%= text_field_tag :query, params[:query], class: "form-control", list: "hints", id: "collection_search", autocomplete: "off" %>
              <div class="input-group-btn">
                <button class="btn btn-default" type="submit">
                  <span class="fa fa-search"></span>
                </button>
              </div>
            </div>
            <p class="help-block">Search for collection</p>
          </div>
        </div>
    <% end %>

    <div class="collection-buttons">
      <button class="btn btn-primary free-btn" data-toggle="modal" data-target="#newCollectionModal">
        New collection
      </button>
        <div class="dropdown">
          <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown">
            Sort
            <span class="caret"></span>
          </button>
          <ul class="dropdown-menu pull-right" role="menu" aria-labelledby="dropdownMenu1">
            <li role="presentation" class="dropdown-header">by name</li>
            <li role="presentation"><a role="menuitem" tabindex="-1" href="" id="sort-alfa-col"><span class="fa fa-sort-alpha-asc"></span> Alphabetical</a></li>
            <li role="presentation"><a role="menuitem" tabindex="-1" href="" id="sort-reverse-col"><span class="fa fa-sort-alpha-desc"></span> Reversed</a></li>
            <li role="presentation" class="divider"></li>
            <li role="presentation" class="dropdown-header">by date created</li>
            <li role="presentation"><a role="menuitem" tabindex="-1" href="" id="sort-date-col"><span class="fa fa-long-arrow-down"></span> <span class="fa fa-calendar"></span> Newest</a></li>
            <li role="presentation"><a role="menuitem" tabindex="-1" href="" id="sort-date-rev-col"><span class="fa fa-long-arrow-up"></span> <span class="fa fa-calendar"></span> Oldest</a></li>
            <li role="presentation" class="divider"></li>
            <li role="presentation" class="dropdown-header">by last modifiaction</li>
            <li role="presentation"><a role="menuitem" tabindex="-1" href="" id="sort-mod-col"><span class="fa fa-long-arrow-down"></span> <span class="fa fa-wrench"></span> Recent</a></li>
            <li role="presentation"><a role="menuitem" tabindex="-1" href="" id="sort-mod-rev-col"><span class="fa fa-long-arrow-up"></span> <span class="fa fa-wrench"></span> Old</a></li>
          </ul>
        </div>
       </div>
  </div>
</div>

<div id="collections-search-results-count">
  <%= render 'collections/collectionscounter' %>
</div>

<%= hidden_field_tag :add_item, params[:add_item], :id => "item-id" %>

<div id="collections-search-results" class="underlined">
    <%= render 'collections/collectionslist', collections: @collections %>
</div>

<% @collection = Collection.new %>
<%= my_modal("newCollectionModal", "New collection") do %>
    <%= render "collections/form", button_name: "Create" %>
<% end %>

app/views/collections/index.js.erb
$('#collections-search-results').html('<%= escape_javascript(render 'collections/collectionslist', collections: @collections) %>');
$('#collections-search-results-count').html('<%= escape_javascript(render('collections/collectionscounter')) %>');


<% if params[:query] == "" %>
  $('#collections-search-results-count').hide();
<% else %>
  $('#collections-search-results-count').show();
<% end %>

handleCollectionSlideshows();

app/views/collections/new.html.erb
<h1 class="mainpage_header">New collection</h1>

<% content_for :buttons do %>
    <li><%= cancel_to collections_path %></li>
<% end %>

<div class="col-sm-8 col-sm-offset-2 col-md-8 col-md-offset-2">
  <%= render 'form' %>
</div>

app/views/collections/public_share.js.erb
$("[id=share-form-button_<%= @permissible.class.name + '-' + @permissible.id.to_s %>]").each(function() {
    $(this).html("<%= escape_javascript(render partial: 'permissible/share_button', object: @permissible) %>")
});

app/views/collections/public_unshare.js.erb
$("[id=share-form-button_<%= @permissible.class.name + '-' + @permissible.id.to_s %>]").each(function() {
    $(this).html("<%= escape_javascript(render partial: 'permissible/share_button', object: @permissible) %>")
});

app/views/collections/show.html.erb
<h2 class="mainpage_header collection">
  <%= @collection.name %> Collection
</h2>
<p>
  Last modified at <%= @collection.updated_at %>
</p>
<p class="collection-desc">
  <%= @collection.description %>
</p>

<div class="collection-buttons underlined">
  <% if @collection.user == current_user %>
  <%= link_to 'Add new item', new_collection_element_path(@collection), class: "btn btn-primary free-btn" %>
  <%= share_button @collection %>
  <% end %>
  <div class="dropdown sort-dropdown">
    <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown">
      Sort
     <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
      <li role="presentation" class="dropdown-header">by name</li>
      <li role="presentation"><a role="menuitem" tabindex="-1" href="#" id="sort-alfa"><span class="fa fa-sort-alpha-asc"></span> Alphabetical</a></li>
      <li role="presentation"><a role="menuitem" tabindex="-1" href="" id="sort-reverse"><span class="fa fa-sort-alpha-desc"></span> Reversed</a></li>
      <li role="presentation" class="divider"></li>
      <li role="presentation" class="dropdown-header">by date created</li>
      <li role="presentation"><a role="menuitem" tabindex="-1" href="" id="sort-date"><span class="fa fa-long-arrow-down"></span> <span class="fa fa-calendar"></span> Newest</a></li>
      <li role="presentation"><a role="menuitem" tabindex="-1" href="" id="sort-date-rev"><span class="fa fa-long-arrow-up"></span> <span class="fa fa-calendar"></span> Oldest</a></li>
      <li role="presentation" class="divider"></li>
      <li role="presentation" class="dropdown-header">by last modifiaction</li>
      <li role="presentation"><a role="menuitem" tabindex="-1" href="" id="sort-mod"><span class="fa fa-long-arrow-down"></span> <span class="fa fa-wrench"></span> Recent</a></li>
      <li role="presentation"><a role="menuitem" tabindex="-1" href="" id="sort-mod-rev"><span class="fa fa-long-arrow-up"></span> <span class="fa fa-wrench"></span> Old</a></li>
    </ul>
  </div>
  <ul class="change-view">
    <li>
      <a href="" id="collection-shelf" class="active-view">
        <i class="fa fa-th fa-lg"></i>
      </a>
    </li>
    <li>
      <a href="" id="collection-carousel">
        <i class="fa fa-th-large fa-lg"></i>
      </a>
    </li>
    <li>
      <a href="" id="collection-list">
        <i class="fa fa-th-list fa-lg"></i>
      </a>
    </li>
    <% if @collection.user == current_user %>
    <li>
      <a href="<%= edit_collection_path(@collection) %>" id="collection-list">
        <i class="fa fa-cog fa-lg"></i>
      </a>
    </li>
    <% end %>
  </ul>
</div>

<div class="collection-view">
  <% unless @elements.empty? %>

    <div class="collection_carousel">
      <%= render 'collections/collectioncarousel' %>
    </div>

    <div class="collection-grid active underlined">
        <%= render 'collections/collectiongrid' %>
    </div>

    <div class="collection_listed">
        <%= render 'collections/collectionlist' %>
    </div>

    <% else %>
      <h3>This collection is empty!</h3>
    <% end %>
</div>