config/routes.rb
Rails.application.routes.draw do

  get 'errors/not_found'

  get 'errors/unacceptable'

  get 'errors/internal_error'

  get 'errors/under_construction'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :activities
  resources :reports
  resources :relationships, only: [:create, :destroy]

  concern :permissible do
    post :public_share
    post :public_unshare
  end

  root 'static_pages#home'

  get 'static_pages/help'
  get 'static_pages/home'

  get "/404", :to => "errors#not_found"
  get "/422", :to => "errors#unacceptable"
  get "/500", :to => "errors#internal_error"
  get "/underconst", :to => "errors#under_construction"

  resources :collections do
    collection do
      get :autocomplete
      get :name_available
    end
    resources :elements
    member do
      concerns :permissible
      get :load_slideshow
    end
  end

  resources :items do
    collection do
      get :autocomplete
    end
    root to: 'items#index'
  end

  resources :posts

  get 'search/results'

  devise_for :users,
             :controllers => {
                 :registrations => 'registrations',
                 :user_profiles => 'user_profiles'
             }

  devise_scope :user do
    get :username_available, controller: "registrations"
    get :email_available, controller: "registrations"
  end

  resources :user_profiles do
    collection do
      get :autocomplete
    end
    member do
      get '/following', to: "relationships#index"
      get '/social', to: "social#index"
      get "/following_list", to: "social#following_list", as: "following_list"
    end
    resources :circles, path: "/followers"
    get "/set_users", to: "circles#set_users", as: "set_users"
  end

  concern :votable do
    member do
      put :upvote
      put :downvote
      put :unvote
    end
  end

  concern :commentable do
    resources :comments, concerns: :votable
  end

  resources :comments, concerns: :commentable, shallow: true

  resources :items, concerns: :commentable, shallow: true

  resources :collections, shallow: true do
    resources :elements, concerns: :commentable
  end

  mount Markitup::Rails::Engine, at: "markitup", as: "markitup"

end

app/models/element.rb
class Element < ActiveRecord::Base
  include Commentable
  include PublicActivity::Model
  tracked except: :destroy,owner: ->(controller, model) { controller && controller.current_user }

  belongs_to :collection
  belongs_to :item

  validates :item_id, :presence => true, uniqueness: { scope: :collection }
  validates :collection_id, :presence => true

  validates :item, :presence => true
  validates :collection, :presence => true

  validates :item_id, :uniqueness => { :scope => :collection_id}

  validates :description, length: { maximum: 600 }

  mount_uploader :image, ItemImageUploader

  def link(collection, item)
    self.collection = collection
    self.item = item
  end

  def name
    self.item.name
  end

  def get_image
    if self.image.blank?
      self.item.image
    else
      self.image
    end
  end

  def item_attributes
    ItemAttribute.get_all user_id: owner_id, item_id: item_id
  end

  # ovverride description getter with special logic
  def description
    attributes["description"] || self.item.description
  end

  def owner_id
    collection.user_id
  end

  def activity_visible_to?(user)
    self.collection ? self.collection.visible_to?(user) : false
  end

  def comment_visible_to?(user)
    self.collection ? self.collection.visible_to?(user) : false
  end
end

app/controllers/elements_controller.rb
class ElementsController < ApplicationController
  include CommentableController

  before_action :get_collection
  before_action :set_element, only: [:show, :edit, :update, :destroy]
  before_action :set_item, only: [:show, :edit, :update]
  before_action :set_attributes, only: [:show, :edit, :update, :destroy]
  before_action :check_owner, only: [:edit, :update, :destroy]
  # before_action :authenticate_user!

  # GET /items/1
  # GET /items/1.json
  def show
    unless @collection.elements.include? @element
      flash[:error] = "Requested item not found"
      redirect_to collection_path(@collection)
    end

    @ago = (Date.today - @element.item.created_at.to_date).to_i
  end

  # GET /items/new
  def new
    if params[:item_id]
      @item = Item.find(params[:item_id])
      if @collection.items.include? @item
        element = Element.where(collection_id: @collection.id, item_id: @item.id).first
        redirect_to collection_element_path(@collection, element) and return
      end
      @element = Element.new item: @item, collection: @collection
      @attributes = @element.item_attributes
    else
      cookies[:collection_redirect_cookie] = params[:collection_id]
      redirect_to items_path(:collection_id => params[:collection_id])
    end
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    item = Item.find(params[:item_id])

    @element = Element.new(element_params)
    @element.link(@collection, item)

    if element_params[:description] == item.description
      @element.description = nil
    end

    saved = @element.save
    @collection.touch if saved
    @attributes = saved ? ItemAttribute.parse(current_user.id, item.id, params[:element]) : []

    respond_to do |format|
      if saved && ItemAttribute.update(current_user.id, item.id, @attributes)
        format.html { redirect_to [@collection, @element], notice: 'Item was successfully created.' }
        format.json { render action: 'show', status: :created, location: @element }
      else
        format.html { render action: 'new' }
        format.json { render json: @element.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    update_image

    saved = @element.update(element_params)
    @attributes = saved ? ItemAttribute.parse(current_user.id, @element.item_id, params[:element]) : []

    if saved && ItemAttribute.update(current_user.id, @element.item_id, @attributes)
      @collection.touch
      redirect_to [@collection, @element], notice: 'Item was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @element.destroy
    @collection.touch
    respond_to do |format|
      format.html { redirect_to collection_path(@collection) }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_element
    begin
      @element = Element.find(params[:id])

      unless @collection.user_id == current_user.id || @collection.visible_to?(current_user)
        redirect_to(root_path)
      end
    rescue
      redirect_to @collection
    end
  end

  def set_item
    @item = Item.find(@element.item_id) unless @element.nil?
  end

  def set_commentable
    @commentable = Element.find_by_id(params[:id])
  end

  def get_collection
    begin
      unless Collection.exists?(params[:collection_id])
        redirect_to collections_path
      end

      @collection = Collection.find(params[:collection_id])

      unless @collection.user_id == current_user.id || @collection.visible_to?(current_user)
        redirect_to(collections_path, alert: "Access forbidden", status: :forbidden)
      end
    rescue
      @collection = nil
    end
  end

  def check_owner
    unless @collection.user_id == current_user.id
      redirect_to(collections_path, alert: "Access forbidden", status: :forbidden)
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def element_params
    params[:element].permit(:item_id, :description, :image, :remove_image, :remote_image_url, :image_cache, :attributes)
  end

  def set_attributes
    @attributes = @element.item_attributes if @element
  end

  def update_image
    unless element_params[:image].blank? && element_params[:remote_image_url].blank?
      @element.remove_image!
    end

    unless @element.save
      redirect_to @element, alert: "Unable to update image."
    end
  end
end

app/helpers/elements_helper.rb
module ElementsHelper
  def item_attribute(builder, type)
    case type
      when "date"
        field = "date_field"
      when "decimal"
        field = "number_field"
      when "state"
        field = "check_box"
      else
        field = "text_field"
    end

    content_tag :p do
      safe_join([builder.text_field(:name), builder.send(field, :value), builder.hidden_field(:type)])
    end
  end

  def hide_if(value)
    "display:none" if value
  end

  def generic_attribute(builder)
    render("attribute", f: builder, i: "index_placeholder", attr: (ItemAttribute.new type: "string"))
  end

  def link_to_add_attribute(builder)
    html = generic_attribute(builder)
    label_tag "new_attr", "Add new attribute", class: "btn btn-primary add-attr-btn", onclick: "add_attribute(this, \"#{escape_javascript(html)}\")"
  end
end

app/views/elements/_attribute.html.erb
<div class="item_attribute">
  <%= f.fields_for "attributes[#{i}]", attr do |a| %>
      <%= a.text_field :name, placeholder: "Attribute name" %>
      <%= a.text_field :value, class: "string_type", disabled: attr.type != "string", style: hide_if(attr.type != "string"), placeholder: "value" %>
      <%= a.date_field :value, class: "date_type", disabled: attr.type != "date", style: hide_if(attr.type != "date") %>
      <%= a.check_box :value, class: "state_type", disabled: attr.type != "state", checked: attr.value, style: hide_if(attr.type != "state") %>
      <%= a.number_field :value, class: "decimal_type", step: "any", disabled: attr.type != "decimal", style: hide_if(attr.type != "decimal"), placeholder: 0 %>
      <%= a.select :type, options_for_select([["State", "state", selected: attr.type == "state"],
                                              ["String", "string", selected: attr.type == "string"],
                                              ["Numerical", "decimal", selected: attr.type == "decimal"],
                                              ["Datetime", "date", selected: attr.type == "date"]]),
                   {}, class: "type_selector", onchange: "field_type_change(this)" %>
      <%= label_tag "destroy_attr", "Remove", class: "btn btn-primary", onclick: "remove_attribute(this)" %>
  <% end %>
</div>

app/views/elements/_form.html.erb
<% if @element.errors.any? %>
    <div class="row">
      <div class="bs-callout bs-callout-danger">
        <h4><%= pluralize(@element.errors.count, "error") %> prohibited this item from being saved:</h4>
        <ul>
          <% @element.errors.full_messages.each do |message| %>
              <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    </div>
<% end %>

<%= form_for @element, :html => {:multipart => true, :id => "element-form"}, url: { action: action }, method: method do |f| %>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: "form-control free-input", rows: 3, value: @element.description, counter: 600 %>
    </div>

    <% @attributes.each_with_index do |attr, index| %>
        <%= render("attribute", attr: attr, f: f, i: index) unless attr.value.nil? %>
    <% end %>

    <%= link_to_add_attribute f %>

    <%= hidden_field_tag "item_id", @element.item_id %>
    <%= hidden_field_tag "collection_id", @element.collection_id %>

    <div class="form-group">
      <%= f.label :image %>
      <%= image_upload f, :image, preview_image: @element.get_image.thumb.url %>
    </div>

    <div class="buttons-group">
      <ul class="horizontal">
        <li><%= f.submit nil, class: "btn btn-primary free-btn" %></li>
        <%= yield :buttons %>
      </ul>
    </div>
<% end %>

app/views/elements/edit.html.erb
<h1 class="mainpage_header">
  <%= @item.name %>
  <small>Edit</small>
</h1>

<% content_for :buttons do %>
    <li><%= cancel_to [@collection, @element] %></li>
<% end %>

<div class="col-sm-8 col-sm-offset-2 col-md-8 col-md-offset-2">
  <%= render 'form', action: "update", method: "patch" %>
</div>

app/views/elements/new.html.erb
<h1 class="mainpage_header"><%= @item.name %></h1>
<p class="well">
  You are going to add this item to your collection <strong><%= @collection.name %></strong>.
  You can modify this item's attributes here and all the changes will be
  visible only when viewing this item in one of your collections,
  so don't hesitate to add anything personal, remove information you don't need or edit existing attributes.
</p>

<% content_for :buttons do %>
    <li><%= cancel_to collection_path(@collection) %></li>
<% end %>

<div class="col-sm-8 col-sm-offset-2 col-md-8 col-md-offset-2">
  <%= render 'form', action: "create", method: "post" %>
</div>

app/views/elements/show.html.erb
<% content_for :container_type, "container-fluid stretched" %>

<div id="item-wrapper" class="container-fluid container-md-stretched col-top">
  <div class="row row-md-stretched">
    <div id="item-showcase" class="col-md-5 col-md-stretched no-padding">
      <% if @element.get_image.standard.url %>
      <a class="fancybox" href="<%= @element.get_image.standard.url %>">
        <%= image_or_placeholder @element.get_image.standard.url %>
      </a>
      <% else %>
        <%= image_or_placeholder @element.get_image.standard.url %>
      <% end %>
      <ul id="item-social-opts">
        <li>
        </li>
      </ul>
    </div>

    <div id="item-info" class="col-md-7 col-md-stretched col-top">
      <% unless @element.item.user.nil? %>
          <div id="item-creation-info" class="pull-right">
            <%= user_avatar @element.item.user.user_profile, nil, "avatar" %>
            <p>
              Created by
              <%= link_to user_profile_path(@element.item.user) do %>
                  <strong><%= @element.item.user.name_or_username %></strong></a>
              <% end %>
              <i>
                <% if @ago.between?(1, 14)  %>
                    <%= pluralize(@ago, "day") %> ago
                <% elsif @ago == 0 %>
                    today
                <% else %>
                    on <%= @element.item.created_at.to_date %>
                <% end %>
              </i>
            </p>
          </div>
      <% end %>
      <h1>
        <%= @element.name %>
        <small>
          from
          <%= link_to @element.collection.name, @element.collection %>
        </small>
      </h1>
      <p class="description">
        <%= @element.description %>
      </p>

      <div id="item-attributes" class="row">
        <% attr_per_col = @attributes.length / 2 %>
        <% attr_per_col = (attr_per_col > 0) ? attr_per_col : 1 %>
        <% @attributes.each_slice(attr_per_col) do |attr_slice| %>
            <div class="col-md-6">
              <dl>
                <% attr_slice.each do |attr| unless attr.value.nil? %>
                        <dt><%= label_tag attr.name, attr.name %></dt>
                        <dd><%= label_tag attr.value.to_s, attr.value.to_s %></dd>
                    <% end end %>
              </dl>
            </div>
        <% end %>
      </div>
      <% if @collection.user == current_user %>
      <ul id="item-opts" class="horizontal">
        <li>
          <%= link_to "Edit", edit_collection_element_path(@collection, @element), class: "btn btn-default" %>
        </li>
        <li>
          <%= link_to [@collection, @element], method: :delete, data: { confirm: "Are you sure you want to remove this element?\nThis action is irreversible!" }, class: "btn btn-default" do %>
              <i class="fa fa-trash"></i>
          <% end %>
        </li>
      </ul>
      <% end %>

    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <%= comment_form @commentable, @comment %>
      <%= comments_list @commentable, @comments %>
    </div>

    <div class="col-md2">
    </div>
  </div>
</div>