config/routes.rb
Rails.application.routes.draw do

  get 'errors/not_found'

  get 'errors/unacceptable'

  get 'errors/internal_error'

  get 'errors/under_construction'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :activities
  resources :reports
  resources :relationships, only: [:create, :destroy]

  concern :permissible do
    post :public_share
    post :public_unshare
  end

  root 'static_pages#home'

  get 'static_pages/help'
  get 'static_pages/home'

  get "/404", :to => "errors#not_found"
  get "/422", :to => "errors#unacceptable"
  get "/500", :to => "errors#internal_error"
  get "/underconst", :to => "errors#under_construction"

  resources :collections do
    collection do
      get :autocomplete
      get :name_available
    end
    resources :elements
    member do
      concerns :permissible
      get :load_slideshow
    end
  end

  resources :items do
    collection do
      get :autocomplete
    end
    root to: 'items#index'
  end

  resources :posts

  get 'search/results'

  devise_for :users,
             :controllers => {
                 :registrations => 'registrations',
                 :user_profiles => 'user_profiles'
             }

  devise_scope :user do
    get :username_available, controller: "registrations"
    get :email_available, controller: "registrations"
  end

  resources :user_profiles do
    collection do
      get :autocomplete
    end
    member do
      get '/following', to: "relationships#index"
      get '/social', to: "social#index"
      get "/following_list", to: "social#following_list", as: "following_list"
    end
    resources :circles, path: "/followers"
    get "/set_users", to: "circles#set_users", as: "set_users"
  end

  concern :votable do
    member do
      put :upvote
      put :downvote
      put :unvote
    end
  end

  concern :commentable do
    resources :comments, concerns: :votable
  end

  resources :comments, concerns: :commentable, shallow: true

  resources :items, concerns: :commentable, shallow: true

  resources :collections, shallow: true do
    resources :elements, concerns: :commentable
  end

  mount Markitup::Rails::Engine, at: "markitup", as: "markitup"

end

app/models/user_profile.rb
class UserProfile < ActiveRecord::Base
  include PublicActivity::Model
  tracked except: [:destroy,:create],owner: ->(controller, model) { controller && controller.current_user }
  belongs_to :user
  validates :name, length: { maximum: 50 }
  validates :description, length: { maximum: 1000 }

  mount_uploader :avatar, AvatarUploader

  def activity_visible_to?(user)
    true
  end
end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController
  before_action :set_user_profile, only: [:index, :show, :edit, :update, :destroy]
  # before_action :check_user_existence
  # before_action :authenticate_user!

  def index
    if params[:query].present?
      @users = User.search params[:query].downcase
    else
      @users = User.all
    end
  end

  def autocomplete
    render json: User.search_user_auto(params[:term].downcase)
  end

  def show
    @shown_user = User.find(params[:id])
    redirect_to(user_profile_path, alert: "Access forbidden", status: :forbidden) unless @shown_user
    @shown_user_profile = @shown_user.user_profile
    @collections = @shown_user.collections.select { |c| c.visible_to?(current_user) }
    @activities = PublicActivity::Activity.order("created_at desc")
    @activities = @activities.select{|a| a.profile_activity?(current_user,@shown_user) }
    
  end

  def edit
  end

  def update
    update_avatar

    respond_to do |format|
      if @user_profile.update(user_profile_params)
        format.html { redirect_to @user_profile, notice: 'Profile was successfully updated.' }
        format.json { render action: 'show', status: :ok, location: @user_profile }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def user_profile_params
    params[:user_profile].permit(:name, :description, :location, :gender, :website, :avatar, :remove_avatar, :remote_avatar_url, :avatar_cache)
  end

  def set_user_profile
    begin
      @user_profile = UserProfile.find_by user_id: current_user.id
      unless @user_profile.user_id == current_user.id
        redirect_to(user_profile_path, alert: "Access forbidden", status: :forbidden)
      end
    rescue
      @user_profile = nil
    end
  end

  def check_user_existence
    redirect_to current_user.user_profile unless User.exists?(params[:id])
  end

  def update_avatar
    unless user_profile_params[:avatar].blank? && user_profile_params[:remote_avatar_url].blank?
      @user_profile.remove_avatar!
    end

    unless @user_profile.save
      redirect_to @user_profile, alert: "Unable to update avatar."
    end
  end
end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
  def resource_name
    :user
  end

  def resource
    @resource = current_user
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def user_avatar(user_profile, version=nil, styles="")
    avatar = user_profile.avatar_url version
    if avatar.nil?
      avatar = "avatar_default.png"
    end
    image_tag avatar, class: styles
  end
end

app/views/user_profiles/_account_settings.html.erb
<h1 class="mainpage_header">
  Profile settings
  <small>Account</small>
</h1>

<div class="col-sm-8 col-sm-offset-2 col-md-8 col-md-offset-2">
  <%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put, id: "sign-up-edit-form" }) do |f| %>
      <%= devise_error_messages! %>

      <div class="form-group">
        <%= f.label :username   %>
        <%= f.text_field :username, autofocus: true, action: username_available_url, class: "form-control free-input" %>
      </div>

      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, action: email_available_url, class: "form-control free-input" %>
      </div>

      <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
          <p>Currently waiting confirmation for: <%= resource.unconfirmed_email %></p>
      <% end %>

      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control free-input", placeholder: "Minimum 8 characters required." %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: "form-control free-input" %>
      </div>

      <div class="form-group">
        <%= f.label :current_password %>
        <%= f.password_field :current_password, class: "form-control free-input" %>
      </div>

      <div class="buttons-group">
        <ul class="horizontal">
          <li><%= f.submit "Update", class: "btn btn-primary free-btn"%></li>
          <li>
            <%=link_to registration_path(resource_name), data: { confirm: "Are you sure you want to delete your account?\nThis action is irreversible!" }, method: :delete, class: "btn btn-default" do %>
                <i class="fa fa-trash"></i>
                Cancel my account
            <% end %>
          </li>
          <li><!--   <%= link_to "Back", :back %> --></li>
          <%= yield :buttons %>
        </ul>
      </div>
  <% end %>
</div>

app/views/user_profiles/_activity_feed.html.erb
<h2>
  Recent activity
</h2>
<% if @activities.length > 0 %>
    <div class="activity">
      <ul class="activity-list">
        <% @activities.take(10).each do |activity| %>
            <%= render_activity(activity) %>
        <% end %>
      </ul>
    </div>
<% else %>
    <strong>
      <%= @shown_user_profile.name != nil && @shown_user_profile.name != '' ? @shown_user_profile.name : @shown_user.username %>
    </strong>
    does not have any activity yet.
<% end %>

app/views/user_profiles/_advanced_settings.html.erb
<h1 class="mainpage_header">
  Profile settings
  <small>Advanced</small>
</h1>

app/views/user_profiles/_collections_settings.html.erb
<h1 class="mainpage_header">
  Profile settings
  <small>Collections</small>
</h1>

app/views/user_profiles/_collectionslist.html.erb
<% @collections.each_slice(4) do |collection_slice| %>
    <div class="item">
      <div class="collections-list row">
        <% collection_slice.each do |collection| %>
          <%= link_to collection do %>
            <div class="col-xs-12 col-sm-6 col-md-3">
              <div class="thumbnail">
                <%= image_tag "bevy_logo.png" %>
                <div class="caption">
                  <h3>
                    <%= link_to collection.name, collection %>
                    <small>Created by: <%= collection.user.name_or_username %></small>
                  </h3>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
<% end %>

app/views/user_profiles/_personal_settings.html.erb
<h1 class="mainpage_header">
  Profile settings
  <small>Personal</small>
</h1>

<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-8 col-centered">
    <%= form_for @user_profile, :html => {:multipart => true, :id => "personal-settings-form"} do |f| %>
        <div class="form-group">
          <%= f.label :avatar %>
          <%= image_upload f, :avatar, preview_image: @user_profile.avatar.thumb.url %>
        </div>

        <div class="form-group">
          <%= f.label :name %>
          <span class="help-block">Give us your full name.</span>
          <%= f.text_field :name, autofocus: true, class: "form-control free-input", counter: 50 %>
        </div>
        <div class="form-group">
          <%= f.label :description %>
          <span class="help-block">What should people know about you? What are your interests? What are your hopes and dreams?</span>
          <%= f.text_area :description, class: "form-control vert textarea", rows: 5, counter: 1000 %>
        </div>
        <div class="form-group">
          <%= f.label :location %>
          <span class="help-block">Share your geographic coordinates or home town.</span>
          <%= f.text_field :location, class: "form-control free-input" %>
        </div>
        <div class="form-group">
          <%= f.label :gender, "Gender" %>
          <span class="help-block">Let us know so we can call you by the appropriate pronoun.</span>
          <%= f.select :gender, [["Male", 1], ["Female", 2], ["N/A", 3]], class: "form-control free-input" %>
        </div>
        <div class="form-group">
          <%= f.label :website %>
          <%= f.text_field :website, class: "form-control free-input" %>
        </div>
        <div class="text-center">
          <%= f.submit "Save changes", class: "btn btn-lg btn-primary free-btn" %>
        </div>
    <% end %>
  </div>
</div>

app/views/user_profiles/_social_settings.html.erb
<h1 class="mainpage_header">
  Profile settings
  <small>Social</small>
</h1>

app/views/user_profiles/_users_list.html.erb
<div class="container-fluid">
  <ul class="users-list row">
    <% users.each do |user| %>
        <li class="col-xs-6 col-sm-4 col-md-3">
          <div class="thumbnail">
            <%= link_to user.profile do %>
                <%= image_or_placeholder user.profile.avatar.thumb.url, placeholder: "avatar_default.png", class: "img-responsive" %>
            <% end %>

            <h4>
              <%= link_to user.profile do %>
                  <%= user.name_or_username %>
              <% end %>
            </h4>
          </div>
        </li>
    <% end %>
  </ul>
</div>

app/views/user_profiles/_userscounter.html.erb
<h3>
  <% if @users.include?(current_user) %>
    <%= pluralize(@users.count - 1, "result") %>
  <% else %>
      <%= pluralize(@users.count, "result") %>
  <% end %>
</h3>

app/views/user_profiles/_usersearch.html.erb
<div id="users-search-bar">
  <div class="row">
    <%= form_tag user_profiles_path, :method => :get, :id => "users-search" do %>
        <div class="col-md-6">
          <div class="form-group">
            <div class="input-group">
              <%= text_field_tag :query, params[:query], class: "form-control", list: "hints", id: "user_search", autocomplete: "off" %>
              <div class="input-group-btn">
                <button class="btn btn-default" type="submit">
                  <span class="glyphicon glyphicon-search"></span>
                </button>
              </div>
            </div>
            <p class="help-block">Search for existing users</p>
          </div>
        </div>
    <% end %>
  </div>
</div>

<div id="users-search-results-count">
  <%= render 'user_profiles/userscounter' %>
</div>
<div id="users-search-results">
  <%= render 'user_profiles/userslist' %>
</div>

app/views/user_profiles/_userslist.html.erb
<ul class="row">
  <% @users.each do |user| %>
      <% unless current_user == user %>
          <li class="col-xs-12 col-sm-6 col-md-3">
            <div class="thumbnail">
              <%= link_to user.user_profile do %>
                <%= image_or_placeholder user.user_profile.avatar.thumb.url, :placeholder => "avatar_default.png", class: "img-responsive" %>
                <div class="caption">
                  <h3>
                    <%= user.username %>
                  </h3>
                </div>
              <% end %>
              <ul class="text-center horizontal">
                <%= follow_button user %>
              </ul>
            </div>
          </li>
      <% end %>
  <% end %>
</ul>

app/views/user_profiles/edit.html.erb
<ul class="nav nav-tabs" role="tablist">
  <li class="active"><a href="#account" role="tab" data-toggle="tab">Account</a></li>
  <li><a href="#personal" role="tab" data-toggle="tab">Personal</a></li>
  <li><a href="<%= errors_under_construction_url %>" class="ucLink">Collections</a></li>    <!-- TODO -->
  <li><a href="<%= errors_under_construction_url %>" class="ucLink">Social</a></li>         <!-- TODO -->
  <li><a href="<%= errors_under_construction_url %>" class="ucLink">Advanced</a></li>       <!-- TODO -->
  <!-- <li><a href="#collections" role="tab" data-toggle="tab">Collections</a></li>   <!-- TODO -->
  <!-- <li><a href="#social" role="tab" data-toggle="tab">Social</a></li>             <!-- TODO -->
  <!-- <li><a href="#advanced" role="tab" data-toggle="tab">Advanced</a></li>         <!-- TODO -->
</ul>

<% if @user_profile.errors.any? %>
    <div class="row">
      <div class="bs-callout bs-callout-danger">
        <h4><%= pluralize(@user_profile.errors.count, "error") %> prohibited this item from being saved:</h4>
        <ul>
          <% @user_profile.errors.full_messages.each do |message| %>
              <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    </div>
<% end %>

<div class="tab-content">
  <div class="tab-pane active" id="account">
    <%= render 'account_settings' %>
  </div>
  <div class="tab-pane" id="personal">
    <%= render 'personal_settings' %>
  </div>
  <div class="tab-pane" id="collections">
    <%= render 'collections_settings' %>
  </div>
  <div class="tab-pane" id="social">
    <%= render 'social_settings' %>
  </div>
  <div class="tab-pane" id="advanced">
    <%= render 'advanced_settings' %>
  </div>
</div>

app/views/user_profiles/index.js.erb
$('#users-search-results').html('<%= escape_javascript(render('user_profiles/userslist')) %>');
$('#users-search-results-count').html('<%= escape_javascript(render('user_profiles/userscounter')) %>');

<% if params[:query] == "" %>
//TODO consider hiding/showig this after adding endlessscroll and pagintation
//$('#users-search-results').hide();
$('#users-search-results-count').hide();
<% else %>
$('#users-search-results').fadeIn(1000);
$('#users-search-results-count').show();
<% end %>

app/views/user_profiles/show.html.erb
<div id="up-header" class="row">
  <div id="up-avatar" class="col-xs-12 col-sm-4 col-md-3 no-padding">
    <a class="fancybox" href="<%= @shown_user_profile.avatar.standard.url %>">
      <%= image_or_placeholder @shown_user_profile.avatar.thumb.url, :placeholder => "avatar_default.png", class: "img-responsive" %>
    </a>

    <ul id="social-opts">
      <li><a class="ucLink" href="<%= errors_under_construction_url %>"><i class="fa fa-facebook"></i></a></li>  <!-- TODO -->
      <li><a class="ucLink" href="<%= errors_under_construction_url %>"><i class="fa fa-twitter"></i></a></li>   <!-- TODO -->
      <li><a class="ucLink" href="<%= errors_under_construction_url %>"><i class="fa fa-youtube"></i></a></li>   <!-- TODO -->
      <li><a class="ucLink" href="<%= errors_under_construction_url %>"><i class="fa fa-instagram"></i></a></li> <!-- TODO -->
      <% if @shown_user_profile.website && !@shown_user_profile.website.empty? %>
          <li><a href="<%= @shown_user_profile.website %>"><i class="fa fa-home"></i></a></li>
      <% end %>
    </ul>
  </div>

  <div id="up-description" class="col-xs-12 col-sm-8 col-md-9">
    <% if @shown_user != current_user %>
        <ul id="up-opts" class="pull-right">
          <li>
            <%= follow_button @shown_user %>
          </li>
          <li>
            <a class="btn btn-default ucLink" href="<%= errors_under_construction_url %>"> <!-- TODO -->
              <i class="fa fa-envelope"></i>
              Message
            </a>
          </li>
        </ul>
    <% end %>

    <h1>
      <%= link_to @shown_user_profile do %>
          <%= @shown_user.name_or_username %>
      <% end %>
      <small><%= @shown_user_profile.location %></small>
    </h1>

    <p class="description"><%= @shown_user_profile.description %></p>

    <div id="up-stats" class="row">
      <div class="col-xs-6 col-sm-3 col-md-3 stats">
        <%= link_to collections_path, class: "count" do %>
            <%= @collections.length %>
        <% end %>
        Collections
      </div>
      <div class="col-xs-6 col-sm-3 col-md-3 stats">
        <a class="count ucLink" href="<%= errors_under_construction_url %>">0</a> <!-- TODO -->
        Items
      </div>
      <div class="col-xs-6 col-sm-3 col-md-3 stats">
        <%= link_to user_profile_circles_path(@shown_user), class: "count" do %>
            <%= @shown_user.followers.distinct.count %>
        <% end %>
        Followers
      </div>
      <div class="col-xs-6 col-sm-3 col-md-3 stats last">
        <%= link_to following_user_profile_path, class: "count" do %>
            <%= @shown_user.followed_users.distinct.count %>
        <% end %>
        Following
      </div>
    </div>
  </div>
</div>

<div id="up-overview">
  <h2 id="up-collections-header">
    Collections
    <i class="chevron fa fa-chevron-up pull-right"></i>
  </h2>

  <% if @collections.length > 0 %>
      <div id="up-collections" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <% @collections.each_slice(4) do |collections| %>
              <div class="item">
                <%= render 'collections/collectionslist', collections: collections %>
              </div>
          <% end %>
        </div>

        <a class="left carousel-control" href="#up-collections" role="button" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left"></span>
        </a>
        <a class="right carousel-control" href="#up-collections" role="button" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right"></span>
        </a>
      </div>
  <% else %>
      <div id="up-collections">
        <strong>
          <%= @shown_user.name_or_username %>
        </strong>
        does not have any collections yet.
      </div>
  <% end %>

  <div class="row">
    <div class="col-md-8">
      <h2 id="up-followers-header">
        Followers
        <i class="chevron fa fa-chevron-up pull-right"></i>
      </h2>

      <div id="up-followers">
        <% if @shown_user.followers.count == 0 %>
            <strong><%= @shown_user.name_or_username %></strong>
            does not have any followers yet.
        <% else %>
            <%= render "user_profiles/users_list", users: @shown_user.followers.distinct %>
        <% end %>
      </div>

      <h2 id="up-following-header">
        Following
        <i class="chevron fa fa-chevron-up pull-right"></i>
      </h2>

      <div id="up-following">
        <% if @shown_user.followed_users.count == 0 %>
            <strong><%= @shown_user.name_or_username %></strong>
            doesn't follow any profile.
        <% else %>
            <%= render "user_profiles/users_list", users: @shown_user.followed_users.distinct %>
        <% end %>
      </div>
    </div>

    <div class="col-md-4 user-activity-feed">
      <%= render 'activity_feed' %>
    </div>
  </div>
</div>