config/routes.rb
Rails.application.routes.draw do

  get 'errors/not_found'

  get 'errors/unacceptable'

  get 'errors/internal_error'

  get 'errors/under_construction'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :activities
  resources :reports
  resources :relationships, only: [:create, :destroy]

  concern :permissible do
    post :public_share
    post :public_unshare
  end

  root 'static_pages#home'

  get 'static_pages/help'
  get 'static_pages/home'

  get "/404", :to => "errors#not_found"
  get "/422", :to => "errors#unacceptable"
  get "/500", :to => "errors#internal_error"
  get "/underconst", :to => "errors#under_construction"

  resources :collections do
    collection do
      get :autocomplete
      get :name_available
    end
    resources :elements
    member do
      concerns :permissible
      get :load_slideshow
    end
  end

  resources :items do
    collection do
      get :autocomplete
    end
    root to: 'items#index'
  end

  resources :posts

  get 'search/results'

  devise_for :users,
             :controllers => {
                 :registrations => 'registrations',
                 :user_profiles => 'user_profiles'
             }

  devise_scope :user do
    get :username_available, controller: "registrations"
    get :email_available, controller: "registrations"
  end

  resources :user_profiles do
    collection do
      get :autocomplete
    end
    member do
      get '/following', to: "relationships#index"
      get '/social', to: "social#index"
      get "/following_list", to: "social#following_list", as: "following_list"
    end
    resources :circles, path: "/followers"
    get "/set_users", to: "circles#set_users", as: "set_users"
  end

  concern :votable do
    member do
      put :upvote
      put :downvote
      put :unvote
    end
  end

  concern :commentable do
    resources :comments, concerns: :votable
  end

  resources :comments, concerns: :commentable, shallow: true

  resources :items, concerns: :commentable, shallow: true

  resources :collections, shallow: true do
    resources :elements, concerns: :commentable
  end

  mount Markitup::Rails::Engine, at: "markitup", as: "markitup"

end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :user

  validates :user_id, :issue_type, :title, :content, presence: true
  validates :title, length: {maximum: 50}
  validates :content, length: {maximum: 500}
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]
  # before_action :authenticate_user!

  # GET /reports
  # GET /reports.json
  def index
    # redirect_to(new_report_path, alert: "Access forbidden") unless current_user.has_role?("Moderator")
    @reports = Report.all
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    # redirect_to(new_report_path, alert: "Access forbidden") unless current_user.has_role?("Moderator")
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
    # redirect_to(new_report_path, alert: "Access forbidden") unless current_user.has_role?("Moderator")
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)
    @report.user_id = current_user.id

    respond_to do |format|
      if @report.save
        format.html { redirect_to root_path, notice: 'Report was successfully created.' }
        format.json { render action: 'show', status: :created, location: root_path }
      else
        format.html { render action: 'new' }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render action: 'show', status: :ok, location: @report }
      else
        format.html { render action: 'edit' }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:user_id, :issue_type, :title, :content)
    end
end

app/views/reports/_form.html.erb
<% if @report.errors.any? %>
    <div class="row">
      <div class="bs-callout bs-callout-danger">
        <h4><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h4>
        <ul>
          <% @report.errors.full_messages.each do |message| %>
              <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    </div>
<% end %>

<%= form_for @report, :html => {:id => "report-form"} do |f| %>
    <div class="form-group">
      <%= f.label :issue_type %>
      <%= f.select :issue_type, [["Problem", "Problem"], ["Idea", "Idea"], ["Opinion", "Opinion"]] %>

      <div class="dropdown issue-type">
        <button class="btn btn-default dropdown-toggle" type="button" id="issue-type-dropdown" data-toggle="dropdown">
          <span class="content"></span>
          <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu" aria-labelledby="issue-type-dropdown">
          <li role="presentation">
            <a role="menuitem" tabindex="-1" href="#" value="Problem">
              <i class="fa fa-warning"></i>
              Problem
            </a>
          </li>
          <li role="presentation">
            <a role="menuitem" tabindex="-1" href="#" value="Idea">
              <i class="fa fa-lightbulb-o"></i>
              Idea
            </a>
          </li>
          <li role="presentation">
            <a role="menuitem" tabindex="-1" href="#" value="Opinion">
              <i class="fa fa-comments-o"></i>
              Opinion
            </a>
          </li>
        </ul>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, autofocus: true, class: "form-control free-input", counter: 50 %>
    </div>
    <div class="form-group">
      <%= f.label :content %>
      <%= f.text_area :content, rows: 5, class: "form-control free-input", counter: 500 %>
    </div>

    <div class="buttons-group">
      <%= f.submit "Send report", class: "btn btn-primary free-btn" %>
    </div>
<% end %>

app/views/reports/edit.html.erb
<h1 class="mainpage_header">Editing report</h1>

<% content_for :buttons do %>
    <li>
      <%= cancel_to @report %>
    </li>
<% end %>

<div class="col-sm-8 col-sm-offset-2 col-md-8 col-md-offset-2">
  <%= render 'form' %>
</div>

app/views/reports/index.html.erb
<button style="float: right" class="btn btn-primary navbar-btn" data-toggle="modal" data-target="#newReportModal">
  New Report
</button>
<h1 class="mainpage_header">Listing reports</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>User</th>
      <th>Email</th>
      <th>Issue type</th>
      <th>Title</th>
      <th>Created at</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @reports = Report.order("created_at desc") %>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.user.username %></td>
        <td><%= report.user.email %></td>
        <td><%= report.issue_type %></td>
        <td><%= link_to truncate(report.title, :length => 100), report %></td>
        <td><%= report.created_at %></td>
        <td><%= link_to 'Show', report %></td>
        <td><%= link_to 'Edit', edit_report_path(report) %></td>
        <td><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% @report = Report.new %>
<%= my_modal("newReportModal", "New report") do %>
    <%= render "reports/form" %>
<% end %>

app/views/reports/new.html.erb
<h1 class="mainpage_header">BEVY Feedback</h1>

<% content_for :buttons do %>
    <li>
      <%= cancel_to static_pages_home_path %>
    </li>
<% end %>

<div class="col-sm-8 col-sm-offset-2 col-md-8 col-md-offset-2">
  <%= render 'form' %>
</div>

app/views/reports/show.html.erb
<h1 class="mainpage_header feedback-header">
    <i class="fa fa-reply-all"></i>
    <%= @report.title %>
    <small><%= @report.issue_type %></small>
</h1>

<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-8 col-centered">
    <table class="table table-hover feedback-table">
      <tr>
        <td>
          <strong>Report ID:</strong>
        </td>
        <td>
          <%= @report.id %>
        </td>
      </tr>
      <tr>
        <td>
          <strong>User:</strong>
        </td>
        <td>
          <%= @report.user.username %>
        </td>
      </tr>
      <tr>
        <td>
          <strong>Email:</strong>
        </td>
        <td>
          <%= @report.user.email %>
        </td>
      </tr>
      <tr>
        <td>
          <strong>Title:</strong>
        </td>
        <td>
          <%= @report.title %>
        </td>
      </tr>
      <tr>
        <td>
          <strong>Content:</strong>
        </td>
        <td>
          <%= h(@report.content).gsub(/\n/, '<br/>').html_safe %>
        </td>
      </tr>
    </table>
  </div>
</div>